### ISSUE TITLE
warn/error if google credentials packages didn't load

### ISSUE THREAD

**Issue by andrewheusser** [tyarkoni/pliers#125] opened 2017-01-31 18:44 UTC
would be helpful for debugging to error out or warn the user if these google credential libraries do not load for whatever reason:

https://github.com/tyarkoni/pliers/blob/master/pliers/google.py#L12

```
try:
    from googleapiclient import discovery, errors
    from oauth2client.client import GoogleCredentials
except ImportError:
    pass
```

happy to submit PR if you agree.

**Comment by adelavega** [comment] 2017-01-31 20:45
I think this is a duplicate of #118 but thanks for the reminde... it's important

**Comment by tyarkoni** [comment] 2017-01-31 21:20
Closing as duplicate, but if you want to submit a PR, that would be great!

**Closed by tyarkoni** 2017-01-31 21:20 UTC
