### ISSUE TITLE
Rregarding specific download options from Pliers

### ISSUE THREAD

**Issue by debanjanghosh** [tyarkoni/pliers#315] opened 2018-11-27 20:22 UTC
Debanjan:

I was wondering whether Pliers support any functionality, similar to NLTK, where users can download a specific model (i.e., interactive installation) as they need it (i.e., vocabulary or say a particular embedding file). 
I explain the situation with an example. Suppose, they users want to experiment with the "fasttext" embedding. Now, instead of allowing the users to download that from the web we can host the embedding as part of Pliers and allow them to download when they need it. Essentially they will be using an interactive installer such as NLTK:
Pliers.download("fasttext")

and once it is downloaded they can use the "fasttext". 
Let me know whether Pliers already have any similar function. Essentially it will be like this - https://www.nltk.org/data.html

Reply from Tal Yarkoni:

Some of the extractors function exactly like that. See e.g. the `PredefinedDictionaryExtractor` and the `TensorFlowInceptionV3Extractor`, both of which download required data files the first time they're invoked. We also use `nltk` for a bunch of extractors, so internally, that downloads data files on demand as well.
There isn't a unified interface for downloading data files at the moment. We could potentially implement one, but I'm not sure it's worth the trouble given that different kind of extractors need to obtain different kinds of data from different sources.

Reply from Francisco Pereira

Thank you for the answer! The reason we were asking is that, for the kinds of models we are looking at (word and sentence embeddings), the distributed files are usually several gigabytes large. It seems like a situation where going for an on-demand download is problematic, as it might take a while and/or be too large for the space available. Hence we were inclined to follow the nltk approach, e.g. tell the user to run a certain function to download the specific model they want to use. For that we would prefer to use a coherent interface, which was why we asked rather than just go ahead and roll our own.

Reply from Tal:

Ah, I see. That sounds like an excellent idea, but that doesn't exist yet. If you're going to write it anyway, it would be great if you could submit a PR with a more general solution. I'm happy to provide pointers if you open an issue or PR.

There's already a support/download.py module (https://github.com/tyarkoni/pliers/blob/b9b843c3e383cea2f5d774d471b5499c4038f7d4/pliers/support/download.py), so a reasonable approach would be to add a generic `download_data()` method there that takes as its first argument the name of the extractor class, and then calls a `_download_data()` class method (optionally) defined inside each extractor.

We should probably settle on a common location to put such files, rather than just dumping them in a tempdir (which is what we do right now). Maybe something like `.pliers/data`. Does that make sense?

Reply from Tal:

There are two ways to go about this that I think would both be reasonable. One would be to create a general-purpose downloader, and then different extractors would all call that to retrieve files. That seems fine, but might need some careful thought to construct an API that would be usable from a variety of different extractors.

The simpler alternative, which might be a better place to start, would be to make only the download invocation interface uniform, and leave it to each extractor to actually download its own files (with the requirement that they go in a similar place). So, for example, the `TensorFlowInceptionV3Extractor` has a `_download_pretrained_model()` instance method that currently retrieves the model files. Rather than rewriting this code to call a common downloader, the suggestion is just to rename this method to something like `_download_data`, and make it a class rather than instance method. Then, when a user calls `download_data("TensorFlowInceptionV3Extractor")` from the command line, that would implicitly call `TensorFlowInceptionV33Extractor._download_data()`, which would execute the existing code (except with the storage directory updated to reflect the common location).

I would suggest starting with the 2nd approach, and then we can always add a file downloading utility that specific extractors could use (if they want to) from inside `_download_data`.

**Comment by adelavega** [comment] 2020-07-16 20:47
This is a dupe of #387 (or the other way around), so I'll close this one

**Closed by adelavega** 2020-07-16 20:47 UTC
